Minor styling fixes
powahftw/InstaStories pull request #15
Opened 2021-03-17 18:38 UTC by mvkv

2021-03-17 19:46 UTC, powahftw requested changes

2021-03-17 19:46 UTC, powahftw commented on static/js/settings.js
> +    res.status === 200 ? "Success!" : `Failure, ${res.error || 'Unknown error'}`;
I'd use null coalescing operator ??

2021-03-17 19:46 UTC, powahftw commented on static/js/settings.js
> +  if (!payload.session_id) {
'session_id' in payload is better.

2021-03-19 21:06 UTC, mvkv commented on static/js/settings.js
> +    res.status === 200 ? "Success!" : `Failure, ${res.error || 'Unknown error'}`;
Done

2021-03-19 21:09 UTC, mvkv commented on static/js/settings.js
> +  if (!payload.session_id) {
Done

2021-03-19 22:10 UTC, powahftw approved these changes

2021-03-31 14:36 UTC, merged